#!/bin/sh
set -eux
lxc launch images:alpine/3.16 TEST
lxc exec TEST sh <<__EE__
apk update 
apk add curl git libgcc gcc musl-dev openssl-dev
set -eux
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "/root/.cargo/env"
git clone https://github.com/ayourtch/async-rust-test-temp
cd async-rust-test-temp
cargo build 
cargo run
__EE__

